### ISSUE TITLE
ESP32 Satellites

### ISSUE THREAD

**Issue by chris-kuhr** [rhasspy/rhasspy#209] opened 2021-04-05 16:44 UTC
Hi *,

I am not yet a rhasspy user and I wanted to ask about the feasability of using multiple ESP32 based satellites. I programmed them myself and they  transmit and receive audio via UDP. They require significantly less power and do not run on a sd card. The implementation wuth i2s mems mic and class-d amp is quite straight forward

I have read the docs only on the surface.
What I think I understood so far, is that MQTT is used for the audio streaming, but I am a bit puzzled on how it all comes together. Is there some sort of sequence diagram?
What would I need to take care of, so that it runs with rhasspy?

Best,
CK

**Comment by Romkabouter** [comment] 2021-04-05 17:30
I recently found that Rhasspy does not work with multiple audiostreams. 
My esp32 streamer works with one, but when I attach another Rhasspy stops responding to the wakeword.
When unplugging one, it starts working again,

Would you be so kind to share your code? I am very interested and maybe I can support UDP in my streamer as well if that is ok with you.

**Comment by chris-kuhr** [comment] 2021-04-05 17:33
I can share the code, no problem, but I don't have it online yet.
Edit: Basically it is put together from arduino examples.

Do you have a clue why rhasspy only manages to process one stream?
Edit: Perhapes I can put some work into it.

The satellite feature is mandatory for my setup.

**Comment by Romkabouter** [comment] 2021-04-05 17:57
I have no clue yet, I only just found because I only used 1 satellite until now.
Here is my repo: https://github.com/Romkabouter/ESP32-Rhasspy-Satellite

**Comment by Romkabouter** [comment] 2021-04-05 18:10
> What I think I understood so far, is that MQTT is used for the audio streaming, but I am a bit puzzled on how it all comes together. Is there some sort of sequence diagram?

The internal messaging is mqtt, but UDP streamingto Rhasspy is possible via Gstreamer input:
https://rhasspy.readthedocs.io/en/latest/audio-input/

Check the GStreamer part at the bottom, you can stream 16bit 16khz data to Rhasspy with this as Audio input:

```
"microphone": {
  "system": "command",
  "command": {
    "record_program": "gst-launch-1.0",
    "record_arguments": "udpsrc port=12333 ! rawaudioparse use-sink-caps=false format=pcm pcm-format=s16le sample-rate=16000 num-channels=1 ! queue ! audioconvert ! audioresample ! filesink location=/dev/stdout",
    "sample_rate": 16000,
    "sample_width": 2,
    "channels": 1
  }
}
```

**Comment by chris-kuhr** [comment] 2021-04-06 16:59
Ok, having gstreamer as connector should work, that is if gstreamer is not as buggy as usual...

I'm using an ESP32-PoE-ISO sold by olimex.com.
Well, I wanted to add the ESP code here, but by doing so realized that it is really messy. First I have to clean it up. Last work on it is half a year old.

But I want to give rhasspy a shot, thus it won't be the time I'm around :-) Although it may take a while until I have something useful.

**Comment by chris-kuhr** [comment] 2021-04-19 12:46
Ok. I have Rhasspy running on an RPi4 now. So far, I could not test the recognition process, becaus my USB mic is broken.
I will directly go for the ESPs. However, I've seen in the docs, that the satellite requires wake word detection. Luckily TensorFlow lite is around these days. But I suppose it will take me a while to get it running on the ESP.

Will report back...

Edit
Sorry, I overlooked your repo link above somehow...
How do you handle the wake word detection?
I am using the arduino ide, so I have no clue at the moment, how to get the i2s i/os running with your code.

**Comment by Romkabouter** [comment] 2021-04-19 15:11
Wakeword detection in done in Rhasspy. Local does not work (yet)
I had Wakenet running, but they seem to have stopped development, I now hope for a procupine library.

UPD audio can be streamed to Rhasspy over the network, Rhasspy can handle the wakeword detection :)

I would suggest using my repo as a base. It has a is2 task which handles reading of a device.
That task also purvblished the wav messages over MQTT, which you might be able to replace with an UDP method

**Comment by chris-kuhr** [comment] 2021-04-19 15:25
How is your reconition latency with MQTT?

As I experimented with pocketsphinx a few years back, I had much better results, when I had fed small chunks (e.g. 128 sample) and not complete utterances to the recognition process via UDP.

edit
Can you point to your i2s code?

**Comment by Romkabouter** [comment] 2021-04-19 17:09
The task is indeed publishing small chunks :)

Search for` void I2Stask(void *p)`

in this file: https://github.com/Romkabouter/ESP32-Rhasspy-Satellite/blob/master/PlatformIO/src/StateMachine.hpp

The data is posted here when you search:
` audioServer.publish(audioFrameTopic.c_str(),(uint8_t *)payload, sizeof(payload));`

**Comment by chris-kuhr** [comment] 2021-04-19 20:59
Ok, I took a look at it.
Two issues here:
1. I use an ESP32-PoE-ISO manufactured by Olimex, which uses Ethernet. I have to look how to fit that in.
2. I use two I2S lines. I have a MEMS mic on the first bus and a class-d amp on a second bus. Thus, I have to make a device for it. I only managed to get them run on seperate buses due to limited clocking schemes.

Any help will be appreciated. :-)

**Comment by Romkabouter** [comment] 2021-04-20 06:46
The publishing of the audio and play of audio is both in the i2s task.
If you first focus on the audio streaming to Rhasspy, you can fit in the rest afterwards :)

A device using ethernet, that's intresting!

**Comment by Romkabouter** [comment] 2021-04-24 08:07
> I recently found that Rhasspy does not work with multiple audiostreams.
> My esp32 streamer works with one, but when I attach another Rhasspy stops responding to the wakeword.
> When unplugging one, it starts working again,

I have made a fix but it is not ready yet.

The problem is that there is 1 wakeword engine running. But the audiobuffers are coming in from multiple streams and are therefore mixed.
Wakeword detection fails on that.

I have changed this to have a wakeword engine and audiobuffer per site_id.
This works, but I have some cleanup to do :)

**Comment by h4de5** [comment] 2021-04-26 08:00
is it possible that this wake word from multiple satellites issue is related? https://github.com/rhasspy/rhasspy/issues/152

**Comment by Romkabouter** [comment] 2021-04-26 08:58
Yes, I think it is.
The wakeword is subscibed to the audiotopic for each satellite.
Then this happens

- audio from sat 1
- audio from sat 1
- audio from sat 2
- audio from sat 1
- audio from sat 2
- audio from sat 2

Those audio frames are processed to 1 audio buffer and 1 wakeword engine (I was testing with porcupine)
All those buffers get mixed up and wakeword detection fails.

I have changed this by adding audiobuffers and wakeword engines per satellite.
This works for porcupine now but I have to commit and do all pull requests stuff after some tidy up of the code.

**Comment by h4de5** [comment] 2021-06-05 07:00
any news on that? or is there a patch I could apply in the meantime? my rpi0s keep crashing when I enable local wake word detection :(

**Comment by Romkabouter** [comment] 2021-06-05 07:35
Local wake word detection does not work, so enabling might cause strange issue.

The solution for multple sats is merged into rhasspy master for the wakeword engine mycroft.

**Comment by h4de5** [comment] 2021-06-05 13:52
so this needs to be fiyed for each engine separately? too bad - I use snowboy, due to the avx requirements of mycroft :(

**Comment by h4de5** [comment] 2021-06-05 13:53
can you link the PR - maybe i can fix it for snowboy too.
/edit: nevermind, there was only one ;)
https://github.com/rhasspy/rhasspy-wake-precise-hermes/pull/1

**Comment by Romkabouter** [comment] 2021-06-05 15:02
I have also created PR's on the other wakeword engines, except Raven.
Those are not yet in master

**Comment by synesthesiam** [comment] 2021-06-16 19:07
These are in `master` (except for Raven). I've also added the ability to have raw UDP audio come in through multiple streams. When the wake word is detected, it automatically forwards the audio over MQTT to the rest of the Rhasspy services.

**Closed as completed** 2021-11-23 21:54 UTC
