### ISSUE TITLE
Bug install V 2.5.9

### ISSUE THREAD

**Issue by arpagor62970** [rhasspy/rhasspy#166] opened 2021-01-17 05:24 UTC
at the make install i have this error 
> running install_egg_info
Writing /home/pi/rhasspy/.venv/lib/python3.7/site-packages/monotonic_align-0.0.0.egg-info
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: flask==1.1.2 in /home/pi/rhasspy/.venv/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.1.2)
ERROR: Could not find a version that satisfies the requirement gruut~=0.5.0
ERROR: No matching distribution found for gruut~=0.5.0
make: *** [Makefile:177: install-rhasspy] Error 1

**Comment by solhuebner** [comment] 2021-01-22 04:42
The VERSION file in the release (archive) of gruut states 0.4.0 and might cause the issues. I opened an issue on the gruut repo.

**Comment by lawrence-iviani** [comment] 2021-01-24 20:09
Same here

**Comment by aberesek** [comment] 2021-02-20 19:26
Same here ;(

**Comment by synesthesiam** [comment] 2021-04-23 18:49
Hopefully fixed in 2.5.10. Please re-open if the problem is still there.

**Closed as completed by synesthesiam** 2021-04-23 18:49 UTC
Labels: bug
