### ISSUE TITLE
webhook awake not working with custom siteId

### ISSUE THREAD

**Issue by KiboOst** [rhasspy/rhasspy#35] opened 2020-05-06 07:18 UTC
When using default as siteId, I got webhook/awake posted to 

```json
"webhooks": {
        "awake": [
            "http://..."
        ]
    }
```

If I rename siteId to anything other than default, no webhook received.

**Comment by KiboOst** [comment] 2020-05-17 11:27
Any news one this ?

**Comment by synesthesiam** [comment] 2020-05-17 13:24
Got it fixed this morning! Will be in the next Docker image :)

**Comment by KiboOst** [comment] 2020-05-21 08:53
Hi,
Just updated and it works with last docker.
But 2.5.0-pre-arm32v6 not updated ;-)

**Comment by koenvervloesem** [comment] 2020-05-21 10:02
If I read commit https://github.com/rhasspy/rhasspy-voltron/commit/c26c55743077ad839c15c8432c5961cf6b834fb9 correctly, the arm32v6 build should now be unified in the main Docker image with tag `2.5.0-pre`. Can you try?

@synesthesiam I also notice that the image with the tag `latest` hasn't been updated recently. Shouldn't `latest` be the same as `2.5.0-pre`? Or what's the reasoning?

**Comment by KiboOst** [comment] 2020-05-21 11:06
Hmm sorry, but rhasspy/rhasspy:2.5.0-pre doesn't work on pi0
It start and come back to console, but no message, and no accessible interface. http api is 404 also, and in profile supervisord files are not updated.

**Comment by koenvervloesem** [comment] 2020-05-21 11:14
Nothing special in the logs of the Docker container?

**Comment by KiboOst** [comment] 2020-05-21 11:15
How can I check that ? Nothing when starting the container.

**Comment by koenvervloesem** [comment] 2020-05-21 11:16
Have a look at the container ID or name with `docker ps` and then execute `docker logs -f NAME_OR_ID`.

**Comment by KiboOst** [comment] 2020-05-21 11:18
Ever tried that but nothing returned, just back to console
docker ps show status Restarting (132) 17 seconds ago

**Comment by koenvervloesem** [comment] 2020-05-21 11:21
That's not good. Try running the docker command for the container with `-ti` instead of `-d` to see the output immediately, this should show you what's going wrong.

**Comment by KiboOst** [comment] 2020-05-21 11:28
Just nothing ...

If I start arm32v6 container with -d then do:
```
docker logs rhasspy-server
docker logs --follow rhasspy-server
```
I have entire starting logs

When I do the same with 2.5.0-pre just nothing. With option -d or -it I can't see any log/return

**Comment by KiboOst** [comment] 2020-05-21 11:31
If you need, Mike know how to connect with both interface and ssh to my pi0 satellite.

**Comment by KiboOst** [comment] 2020-05-21 11:36
Are you sure 2.5-pre should works on pi0 ?? Did anyone ever tried it ?

**Comment by koenvervloesem** [comment] 2020-05-21 11:46
I'm not sure, I haven't tried it yet, you're probably the first :-) @synesthesiam can probably shed some light on whether this should work because of https://github.com/rhasspy/rhasspy-voltron/commit/c26c55743077ad839c15c8432c5961cf6b834fb9.

**Comment by synesthesiam** [comment] 2020-05-21 15:43
I'm also having trouble on my Pi 0, @KiboOst. It seems to pull the `amd64` image, even though an `armv6` image is part of the manifest. I can't tell where the problem is yet, but I may have to just maintain a separate image tag for the Pi 0 :(

**Comment by synesthesiam** [comment] 2020-06-02 14:04
Fixed in `master`!

**Closed as completed by synesthesiam** 2020-06-02 14:04 UTC
